Add option to authenticate to secure assets
kontent-ai/data-ops pull request #101
Opened 2024-11-17 13:18 UTC by andgdk

### Motivation

Currently, for environments with [secure assets delivery](https://kontent.ai/learn/docs/security/secure-access/javascript#a-retrieve-assets-securely) enabled, the resulting backup contains assets with a file size of 0 kB in the assets/ folder.

This is critical as for certain users, the backup is incomplete, and no error/warning is provided.

Preposition
Support could be added by providing the bearer token to the fetching of assets.

Only ran unit tests.

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Set up a new environment and contact Kontent.ai support to enable secure asset delivery for at least the `delivery API`.

Partially resolves #100

2024-11-24 14:42 UTC, andgdk commented
Investigating a way to surface warnings to users lead me to the following investigation:
`d4d07406-adfd-404b-bbd5-58c5de6adfd2-kai-hp-highlight-3.jpg` reports a warning when comparing the blob size with the size reported by it's metadata.

`d4d07406-adfd-404b-bbd5-58c5de6adfd2-kai-hp-highlight-3.`__`jpg`__
- `backup.zip`: 27,093 bytes (_baseline_)
- `Kontent.ai` app UI: 26.45 kB (26.45 kB: 27084.8 bytes; 26.46 kb: 27095.04 bytes) (__probably rounding error__)
- Running `backupEnvironment` method:
  - CLI: 27,002 bytes (`res.size`) (__nok__)
  See PR snippet below[^1]
- `2024-11-24-10-21-backup-<UUID>.zip`: 27,002 bytes (__nok__)

I uploaded some random `.jpeg` and `.png` from my disk. Running `backupEnvironment` with the additional files reports errors on those files as well. One with significant difference: Size mismatch: expected 385_657 bytes, got 291_500 bytes (.jpeg).

Because of those results, I have to question my approach in comparing the file size. However, my expectation would still be that `res.size` should always be equal to `asset.size`. Perhaps there is a compression step which is not reflected in the metadata?
What is your take on this @IvanKiral

[^1]: https://github.com/andgdk/kontent-ai-data-ops/blob/2f880a6bf05e925b98992eb7dcae83108f638093/src/modules/backupRestore/backupRestoreEntities/entities/assets.ts#L83-L102

2024-11-26 10:06 UTC, IvanKiral commented
Well, it seems that there is indeed a compression step. I investigated URLs, and they differ for downloading the asset and the public URL for the asset in the UI. Unfortunately, it seems that this is how a product works, and right now, backing up an asset using this tool would mean that it is being compromised (probably some metadata is missing:/). The best we can do is submit feedback on the product if you are interested. 

About secure assets - the use case is not utilized by that many people as far as I know, however, we might merge your solution with slight changes if you would like to. It would mean reverting the last commit and probably in the documentation add some information about the newly added parameter, and probably a link to the Kontent. ai learn (https://kontent.ai/learn/docs/security/secure-access/javascript#a-retrieve-assets-securely). What do you think?

2024-11-30 09:44 UTC, andgdk commented
Hi @IvanKiral,
just pushed the requested changes, please have a look. Please be aware that I did not run integration tests for this PR.

I did not add the result of your investigation regarding a potential compression/metadata modification to the readme.
However, the known limitation section at the end of the `backupRestore` readme might be suited to do so - I leave it up to you.

For enterprise customers I feel the situation regarding the compression should be investigated, at least this needs clarification from my point of view. So, I can contact the support, and mention you as well, if you don't intervene. I would be also happy if you were in the position to keep track of this.

2024-12-06 08:49 UTC, IvanKiral commented
Sorry for the delayed message. We were investigating a bit more and the best thing we can do now is to add a query parameter (?q=100). 

However, the image is still being comprised this way, but not that much (I believe some metadata is still missing). I also like your idea of adding it to the known limitation. Would you like to add it, or do you want me to review it as it is now and we will try to merge it? (so you have a contribution badge)

For more information about this you can refer to https://kontent.ai/learn/docs/apis/image-transformation-api#a-quality-parameter

2024-12-06 15:27 UTC, andgdk commented
> Sorry for the delayed message. We were investigating a bit more and the best thing we can do now is to add a query parameter (?q=100).

Thanks for looking further into this. Did you also experiment with a combination of the [Lossless parameter](https://kontent.ai/learn/docs/apis/image-transformation-api#a-lossless-parameter)?

Unfortunately, I cannot request a review, so I ask this way for a review by you, @IvanKiral

2024-12-09 11:49 UTC, IvanKiral requested changes

2024-12-09 11:49 UTC, IvanKiral commented on README.md
> +**Backing up All Data from an Environment with Secure Asset Delivery Enabled**
I don't think this one is necessary, moreover it doesn't have to be first, as this parameter will probably not be used as widely :) please remove it keep the description in the table in backupRestore readme.

2024-12-09 11:49 UTC, IvanKiral commented on src/commands/environment/backupRestore/README.md
> +| `--secureAssetDeliveryKey` | (Optional) The secure asset delivery API key for the environment.<br />Read more about enabling secure asset delivery in the [Kontent.ai documentation](https://kontent.
please move this after the --exclude parameter

2024-12-09 11:49 UTC, IvanKiral commented on src/commands/environment/backupRestore/README.md
> +- **Asset Quality**: Assets fetched by the tool may be compressed and metadata can be missing. You may find more information about asset compression in the [quality](https://kontent.ai/learn/docs/api
lossles only goes for the images with webp format. Can you please remove the part mentioning it? I think that the quality parameter is enough for reference

2024-12-09 11:49 UTC, IvanKiral commented on src/commands/environment/backupRestore/backup.ts
> +            "You need to provide a asset delivery key when secure asset delivery is enabled for the given Kontent.ai environment.",
a secure asset delivery key

2024-12-09 11:49 UTC, IvanKiral commented on src/modules/backupRestore/backupRestoreEntities/entities/assets.ts
> +  const defaultOptions: RequestInit = {
nitpick: options

2024-12-09 11:49 UTC, IvanKiral commented on src/modules/backupRestore/backupRestoreEntities/entityDefinition.ts
> +    secureAssetDeliveryKey: string | undefined,
can you swap the logOptions and secureAssetDeliveryKey? Just for the consistency, I would like to have logOptions as last parameter :)

2024-12-09 11:49 UTC, IvanKiral commented on src/modules/backupRestore/backupRestoreEntities/entities/assets.ts
> +    .then(res => res.blob()).then(res => res.stream());
When formatting is present, I would have all .then on new lines :)

2024-12-09 11:49 UTC, IvanKiral commented on src/modules/backupRestore/backupRestoreEntities/entities/assets.ts
> +  const file = await fetch(asset.url, defaultOptions)
could you please update the URL with the query parameter `?q=100`? You could use something like string formatting to add it (\`${asset.url}?q=100\`) The images would have better quality then :)

2024-12-10 11:09 UTC, IvanKiral approved these changes

2024-12-10 11:10 UTC, merged

2024-12-10 11:10 UTC, IvanKiral commented
Thanks for the PR, I merged it will release it soon, with some other updates :)

2024-12-19 07:24 UTC, andgdk commented
@IvanKiral Hi, just wanted to share one finding for documentation purpose.
This PR added the quality query parameter `?q=100` to the asset URL. This was requested to improve the asset quality and circumvent potential loss of quality.

Finding:
The file size can increase significantly in some instances, while the approach seam to yield good results most of the time.
Here is an example for increased file size from the `backup.zip`:
```
Exporting: file Screenshot_24-11-2024_121847_github.com.jpeg.
Size mismatch: expected 385657 bytes, got 597346 bytes.
```